# Generated by Django 5.0.6 on 2024-06-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_articles_content_alter_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
